baseURL: "https://kwandev.github.io"
languageCode: "ko"
title: "KwanDev"
theme: "tania"
paginate: 6

params:
  titleEmoji: "😎"
  socialOptions:
    github: "https://github.com/kwandev"
    email: "mailto:rudghks7816@gmail.com"

menu:
  header:
    - name: Articles
      url: "/articles/"
    - name: Tags
      url: "/tags/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

# googleAnalytics: UA-90320470-2
googleAnalytics: G-KTWEFES8PN
